// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: fabricsdk_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BalanceOf
type BalanceOfResuest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner    string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *BalanceOfResuest) Reset() {
	*x = BalanceOfResuest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceOfResuest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceOfResuest) ProtoMessage() {}

func (x *BalanceOfResuest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceOfResuest.ProtoReflect.Descriptor instead.
func (*BalanceOfResuest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceOfResuest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BalanceOfResuest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BalanceOfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num string `protobuf:"bytes,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *BalanceOfResponse) Reset() {
	*x = BalanceOfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceOfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceOfResponse) ProtoMessage() {}

func (x *BalanceOfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceOfResponse.ProtoReflect.Descriptor instead.
func (*BalanceOfResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceOfResponse) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

// OwnerOf
type OwnerOfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId  string `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *OwnerOfRequest) Reset() {
	*x = OwnerOfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnerOfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerOfRequest) ProtoMessage() {}

func (x *OwnerOfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerOfRequest.ProtoReflect.Descriptor instead.
func (*OwnerOfRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{2}
}

func (x *OwnerOfRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *OwnerOfRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type OwnerOfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *OwnerOfResponse) Reset() {
	*x = OwnerOfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OwnerOfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OwnerOfResponse) ProtoMessage() {}

func (x *OwnerOfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OwnerOfResponse.ProtoReflect.Descriptor instead.
func (*OwnerOfResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{3}
}

func (x *OwnerOfResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

// Approve
type ApproveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	TokenId  string `protobuf:"bytes,2,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ApproveRequest) Reset() {
	*x = ApproveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveRequest) ProtoMessage() {}

func (x *ApproveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveRequest.ProtoReflect.Descriptor instead.
func (*ApproveRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{4}
}

func (x *ApproveRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *ApproveRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *ApproveRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ApproveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ApproveResponse) Reset() {
	*x = ApproveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResponse) ProtoMessage() {}

func (x *ApproveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResponse.ProtoReflect.Descriptor instead.
func (*ApproveResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{5}
}

func (x *ApproveResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

// SetApprovalForAll
// ?
type SetApprovalForAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator  string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	Operator2 string `protobuf:"bytes,2,opt,name=operator2,proto3" json:"operator2,omitempty"`
	Username  string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SetApprovalForAllRequest) Reset() {
	*x = SetApprovalForAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetApprovalForAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetApprovalForAllRequest) ProtoMessage() {}

func (x *SetApprovalForAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetApprovalForAllRequest.ProtoReflect.Descriptor instead.
func (*SetApprovalForAllRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{6}
}

func (x *SetApprovalForAllRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *SetApprovalForAllRequest) GetOperator2() string {
	if x != nil {
		return x.Operator2
	}
	return ""
}

func (x *SetApprovalForAllRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SetApprovalForAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *SetApprovalForAllResponse) Reset() {
	*x = SetApprovalForAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetApprovalForAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetApprovalForAllResponse) ProtoMessage() {}

func (x *SetApprovalForAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetApprovalForAllResponse.ProtoReflect.Descriptor instead.
func (*SetApprovalForAllResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{7}
}

func (x *SetApprovalForAllResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

// IsApprovedForAll
type IsApprovedForAllRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner    string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Operator string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *IsApprovedForAllRequest) Reset() {
	*x = IsApprovedForAllRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsApprovedForAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsApprovedForAllRequest) ProtoMessage() {}

func (x *IsApprovedForAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsApprovedForAllRequest.ProtoReflect.Descriptor instead.
func (*IsApprovedForAllRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{8}
}

func (x *IsApprovedForAllRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *IsApprovedForAllRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *IsApprovedForAllRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type IsApprovedForAllResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *IsApprovedForAllResponse) Reset() {
	*x = IsApprovedForAllResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsApprovedForAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsApprovedForAllResponse) ProtoMessage() {}

func (x *IsApprovedForAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsApprovedForAllResponse.ProtoReflect.Descriptor instead.
func (*IsApprovedForAllResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{9}
}

func (x *IsApprovedForAllResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

// GetApproved
type GetApprovedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId  string `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GetApprovedRequest) Reset() {
	*x = GetApprovedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApprovedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApprovedRequest) ProtoMessage() {}

func (x *GetApprovedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApprovedRequest.ProtoReflect.Descriptor instead.
func (*GetApprovedRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetApprovedRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *GetApprovedRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// ?
type GetApprovedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetApprovedResponse) Reset() {
	*x = GetApprovedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApprovedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApprovedResponse) ProtoMessage() {}

func (x *GetApprovedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApprovedResponse.ProtoReflect.Descriptor instead.
func (*GetApprovedResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{11}
}

// TransferFrom
type TransferFromRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From     string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To       string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	TokenId  string `protobuf:"bytes,3,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *TransferFromRequest) Reset() {
	*x = TransferFromRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFromRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFromRequest) ProtoMessage() {}

func (x *TransferFromRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFromRequest.ProtoReflect.Descriptor instead.
func (*TransferFromRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{12}
}

func (x *TransferFromRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransferFromRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferFromRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TransferFromRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type TransferFromResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *TransferFromResponse) Reset() {
	*x = TransferFromResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferFromResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferFromResponse) ProtoMessage() {}

func (x *TransferFromResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferFromResponse.ProtoReflect.Descriptor instead.
func (*TransferFromResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{13}
}

func (x *TransferFromResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

// ClientAccountBalance
type ClientAccountBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ClientAccountBalanceRequest) Reset() {
	*x = ClientAccountBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAccountBalanceRequest) ProtoMessage() {}

func (x *ClientAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*ClientAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{14}
}

func (x *ClientAccountBalanceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ClientAccountBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num string `protobuf:"bytes,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *ClientAccountBalanceResponse) Reset() {
	*x = ClientAccountBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAccountBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAccountBalanceResponse) ProtoMessage() {}

func (x *ClientAccountBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAccountBalanceResponse.ProtoReflect.Descriptor instead.
func (*ClientAccountBalanceResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{15}
}

func (x *ClientAccountBalanceResponse) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

// ClientAccountID
type ClientAccountIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ClientAccountIDRequest) Reset() {
	*x = ClientAccountIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAccountIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAccountIDRequest) ProtoMessage() {}

func (x *ClientAccountIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAccountIDRequest.ProtoReflect.Descriptor instead.
func (*ClientAccountIDRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{16}
}

func (x *ClientAccountIDRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ClientAccountIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X509 string `protobuf:"bytes,1,opt,name=x509,proto3" json:"x509,omitempty"`
}

func (x *ClientAccountIDResponse) Reset() {
	*x = ClientAccountIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAccountIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAccountIDResponse) ProtoMessage() {}

func (x *ClientAccountIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAccountIDResponse.ProtoReflect.Descriptor instead.
func (*ClientAccountIDResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{17}
}

func (x *ClientAccountIDResponse) GetX509() string {
	if x != nil {
		return x.X509
	}
	return ""
}

// TokenURI
type TokenURIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId  string `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *TokenURIRequest) Reset() {
	*x = TokenURIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenURIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenURIRequest) ProtoMessage() {}

func (x *TokenURIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenURIRequest.ProtoReflect.Descriptor instead.
func (*TokenURIRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{18}
}

func (x *TokenURIRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TokenURIRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type TokenURIReqponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	URI string `protobuf:"bytes,1,opt,name=URI,proto3" json:"URI,omitempty"`
}

func (x *TokenURIReqponse) Reset() {
	*x = TokenURIReqponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenURIReqponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenURIReqponse) ProtoMessage() {}

func (x *TokenURIReqponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenURIReqponse.ProtoReflect.Descriptor instead.
func (*TokenURIReqponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{19}
}

func (x *TokenURIReqponse) GetURI() string {
	if x != nil {
		return x.URI
	}
	return ""
}

// SetChainCodeOwner
type SetChainCodeOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CodeOwner string `protobuf:"bytes,1,opt,name=codeOwner,proto3" json:"codeOwner,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SetChainCodeOwnerRequest) Reset() {
	*x = SetChainCodeOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetChainCodeOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChainCodeOwnerRequest) ProtoMessage() {}

func (x *SetChainCodeOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChainCodeOwnerRequest.ProtoReflect.Descriptor instead.
func (*SetChainCodeOwnerRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{20}
}

func (x *SetChainCodeOwnerRequest) GetCodeOwner() string {
	if x != nil {
		return x.CodeOwner
	}
	return ""
}

func (x *SetChainCodeOwnerRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// ?
type SetChainCodeOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *SetChainCodeOwnerResponse) Reset() {
	*x = SetChainCodeOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetChainCodeOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChainCodeOwnerResponse) ProtoMessage() {}

func (x *SetChainCodeOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChainCodeOwnerResponse.ProtoReflect.Descriptor instead.
func (*SetChainCodeOwnerResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{21}
}

func (x *SetChainCodeOwnerResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

// GetChainCodeOwner
type GetChainCodeOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *GetChainCodeOwnerRequest) Reset() {
	*x = GetChainCodeOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChainCodeOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainCodeOwnerRequest) ProtoMessage() {}

func (x *GetChainCodeOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainCodeOwnerRequest.ProtoReflect.Descriptor instead.
func (*GetChainCodeOwnerRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetChainCodeOwnerRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetChainCodeOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *GetChainCodeOwnerResponse) Reset() {
	*x = GetChainCodeOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetChainCodeOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainCodeOwnerResponse) ProtoMessage() {}

func (x *GetChainCodeOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainCodeOwnerResponse.ProtoReflect.Descriptor instead.
func (*GetChainCodeOwnerResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetChainCodeOwnerResponse) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

// SetBaseURI
type SetBaseURIRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri      string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *SetBaseURIRequest) Reset() {
	*x = SetBaseURIRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBaseURIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBaseURIRequest) ProtoMessage() {}

func (x *SetBaseURIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBaseURIRequest.ProtoReflect.Descriptor instead.
func (*SetBaseURIRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{24}
}

func (x *SetBaseURIRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *SetBaseURIRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// ?
type SetBaseURIResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SetBaseURIResponse) Reset() {
	*x = SetBaseURIResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBaseURIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBaseURIResponse) ProtoMessage() {}

func (x *SetBaseURIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBaseURIResponse.ProtoReflect.Descriptor instead.
func (*SetBaseURIResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{25}
}

func (x *SetBaseURIResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// PublicMint
type PublicMintRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *PublicMintRequest) Reset() {
	*x = PublicMintRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicMintRequest) ProtoMessage() {}

func (x *PublicMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicMintRequest.ProtoReflect.Descriptor instead.
func (*PublicMintRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{26}
}

func (x *PublicMintRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type PublicMintResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId string `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
}

func (x *PublicMintResponse) Reset() {
	*x = PublicMintResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicMintResponse) ProtoMessage() {}

func (x *PublicMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicMintResponse.ProtoReflect.Descriptor instead.
func (*PublicMintResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{27}
}

func (x *PublicMintResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

// PrivateBurn
type PrivateBurnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId  string `protobuf:"bytes,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *PrivateBurnRequest) Reset() {
	*x = PrivateBurnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateBurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateBurnRequest) ProtoMessage() {}

func (x *PrivateBurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateBurnRequest.ProtoReflect.Descriptor instead.
func (*PrivateBurnRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{28}
}

func (x *PrivateBurnRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *PrivateBurnRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type PrivateBurnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *PrivateBurnResponse) Reset() {
	*x = PrivateBurnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivateBurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateBurnResponse) ProtoMessage() {}

func (x *PrivateBurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateBurnResponse.ProtoReflect.Descriptor instead.
func (*PrivateBurnResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{29}
}

func (x *PrivateBurnResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

// TotalSupply
type TotalSupplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *TotalSupplyRequest) Reset() {
	*x = TotalSupplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalSupplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalSupplyRequest) ProtoMessage() {}

func (x *TotalSupplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalSupplyRequest.ProtoReflect.Descriptor instead.
func (*TotalSupplyRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{30}
}

func (x *TotalSupplyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type TotalSupplyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num string `protobuf:"bytes,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *TotalSupplyResponse) Reset() {
	*x = TotalSupplyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalSupplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalSupplyResponse) ProtoMessage() {}

func (x *TotalSupplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalSupplyResponse.ProtoReflect.Descriptor instead.
func (*TotalSupplyResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{31}
}

func (x *TotalSupplyResponse) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

// Enroll
type EnrollRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{32}
}

func (x *EnrollRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type EnrollResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X509 string `protobuf:"bytes,1,opt,name=x509,proto3" json:"x509,omitempty"`
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fabricsdk_service_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fabricsdk_service_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_fabricsdk_service_proto_rawDescGZIP(), []int{33}
}

func (x *EnrollResponse) GetX509() string {
	if x != nil {
		return x.X509
	}
	return ""
}

var File_fabricsdk_service_proto protoreflect.FileDescriptor

var file_fabricsdk_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x64, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x10, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x25, 0x0a, 0x11, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x46, 0x0a, 0x0e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x4f,
	0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27,
	0x0a, 0x0f, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x4f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x62, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x41,
	0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x70,
	0x0a, 0x18, 0x53, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x46, 0x6f, 0x72,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x2b, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x46,
	0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x67, 0x0a,
	0x17, 0x49, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x41, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x49, 0x73, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x6f, 0x6b, 0x22, 0x4a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x15,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6f, 0x0a, 0x13, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x39,
	0x0a, 0x1b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x1c, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x34, 0x0a, 0x16, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x2d, 0x0a, 0x17, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x78, 0x35, 0x30, 0x39, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x78, 0x35, 0x30, 0x39,
	0x22, 0x47, 0x0a, 0x0f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x52, 0x49, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x10, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x55, 0x52, 0x49, 0x52, 0x65, 0x71, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x52, 0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x49, 0x22,
	0x54, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x43, 0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x31, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x55, 0x52,
	0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x42, 0x61, 0x73,
	0x65, 0x55, 0x52, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x2f, 0x0a, 0x11, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4d, 0x69,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x12, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4d,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x12, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x42, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x25, 0x0a, 0x13, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x75, 0x72, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x30, 0x0a, 0x12, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x13, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x22, 0x2b, 0x0a, 0x0d, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x24, 0x0a, 0x0e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x78, 0x35, 0x30, 0x39, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x78, 0x35, 0x30, 0x39, 0x32, 0xb7, 0x08, 0x0a, 0x09, 0x46, 0x61, 0x62, 0x72, 0x69,
	0x63, 0x53, 0x44, 0x4b, 0x12, 0x34, 0x0a, 0x09, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4f,
	0x66, 0x12, 0x11, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4f, 0x66, 0x52, 0x65, 0x73,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4f, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x07, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x4f, 0x66, 0x12, 0x0f, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x4f, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x4f, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x07, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x12, 0x0f, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x11, 0x53, 0x65,
	0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x12,
	0x19, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x46, 0x6f, 0x72,
	0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x53, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x10, 0x49, 0x73, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x12, 0x18, 0x2e, 0x49,
	0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x49, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x64, 0x46, 0x6f, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x64, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x12,
	0x14, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x46, 0x72, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55,
	0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x17, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a,
	0x08, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x55, 0x52, 0x49, 0x12, 0x10, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x55, 0x52, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x55, 0x52, 0x49, 0x52, 0x65, 0x71, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x53, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x4f,
	0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x4f, 0x77,
	0x6e, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a,
	0x53, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x55, 0x52, 0x49, 0x12, 0x12, 0x2e, 0x53, 0x65, 0x74,
	0x42, 0x61, 0x73, 0x65, 0x55, 0x52, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x53, 0x65, 0x74, 0x42, 0x61, 0x73, 0x65, 0x55, 0x52, 0x49, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4d,
	0x69, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4d, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4d, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x0b, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x75, 0x72, 0x6e, 0x12, 0x13, 0x2e,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x75, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x42, 0x75, 0x72, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0b, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x2e, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x55, 0x52, 0x49, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x06, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x12, 0x0e, 0x2e,
	0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e,
	0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fabricsdk_service_proto_rawDescOnce sync.Once
	file_fabricsdk_service_proto_rawDescData = file_fabricsdk_service_proto_rawDesc
)

func file_fabricsdk_service_proto_rawDescGZIP() []byte {
	file_fabricsdk_service_proto_rawDescOnce.Do(func() {
		file_fabricsdk_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_fabricsdk_service_proto_rawDescData)
	})
	return file_fabricsdk_service_proto_rawDescData
}

var file_fabricsdk_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_fabricsdk_service_proto_goTypes = []interface{}{
	(*BalanceOfResuest)(nil),             // 0: BalanceOfResuest
	(*BalanceOfResponse)(nil),            // 1: BalanceOfResponse
	(*OwnerOfRequest)(nil),               // 2: OwnerOfRequest
	(*OwnerOfResponse)(nil),              // 3: OwnerOfResponse
	(*ApproveRequest)(nil),               // 4: ApproveRequest
	(*ApproveResponse)(nil),              // 5: ApproveResponse
	(*SetApprovalForAllRequest)(nil),     // 6: SetApprovalForAllRequest
	(*SetApprovalForAllResponse)(nil),    // 7: SetApprovalForAllResponse
	(*IsApprovedForAllRequest)(nil),      // 8: IsApprovedForAllRequest
	(*IsApprovedForAllResponse)(nil),     // 9: IsApprovedForAllResponse
	(*GetApprovedRequest)(nil),           // 10: GetApprovedRequest
	(*GetApprovedResponse)(nil),          // 11: GetApprovedResponse
	(*TransferFromRequest)(nil),          // 12: TransferFromRequest
	(*TransferFromResponse)(nil),         // 13: TransferFromResponse
	(*ClientAccountBalanceRequest)(nil),  // 14: ClientAccountBalanceRequest
	(*ClientAccountBalanceResponse)(nil), // 15: ClientAccountBalanceResponse
	(*ClientAccountIDRequest)(nil),       // 16: ClientAccountIDRequest
	(*ClientAccountIDResponse)(nil),      // 17: ClientAccountIDResponse
	(*TokenURIRequest)(nil),              // 18: TokenURIRequest
	(*TokenURIReqponse)(nil),             // 19: TokenURIReqponse
	(*SetChainCodeOwnerRequest)(nil),     // 20: SetChainCodeOwnerRequest
	(*SetChainCodeOwnerResponse)(nil),    // 21: SetChainCodeOwnerResponse
	(*GetChainCodeOwnerRequest)(nil),     // 22: GetChainCodeOwnerRequest
	(*GetChainCodeOwnerResponse)(nil),    // 23: GetChainCodeOwnerResponse
	(*SetBaseURIRequest)(nil),            // 24: SetBaseURIRequest
	(*SetBaseURIResponse)(nil),           // 25: SetBaseURIResponse
	(*PublicMintRequest)(nil),            // 26: PublicMintRequest
	(*PublicMintResponse)(nil),           // 27: PublicMintResponse
	(*PrivateBurnRequest)(nil),           // 28: PrivateBurnRequest
	(*PrivateBurnResponse)(nil),          // 29: PrivateBurnResponse
	(*TotalSupplyRequest)(nil),           // 30: TotalSupplyRequest
	(*TotalSupplyResponse)(nil),          // 31: TotalSupplyResponse
	(*EnrollRequest)(nil),                // 32: EnrollRequest
	(*EnrollResponse)(nil),               // 33: EnrollResponse
}
var file_fabricsdk_service_proto_depIdxs = []int32{
	0,  // 0: FabricSDK.BalanceOf:input_type -> BalanceOfResuest
	2,  // 1: FabricSDK.OwnerOf:input_type -> OwnerOfRequest
	4,  // 2: FabricSDK.Approve:input_type -> ApproveRequest
	6,  // 3: FabricSDK.SetApprovalForAll:input_type -> SetApprovalForAllRequest
	8,  // 4: FabricSDK.IsApprovedForAll:input_type -> IsApprovedForAllRequest
	10, // 5: FabricSDK.GetApproved:input_type -> GetApprovedRequest
	12, // 6: FabricSDK.TransferFrom:input_type -> TransferFromRequest
	14, // 7: FabricSDK.ClientAccountBalance:input_type -> ClientAccountBalanceRequest
	16, // 8: FabricSDK.ClientAccountID:input_type -> ClientAccountIDRequest
	18, // 9: FabricSDK.TokenURI:input_type -> TokenURIRequest
	20, // 10: FabricSDK.SetChainCodeOwner:input_type -> SetChainCodeOwnerRequest
	22, // 11: FabricSDK.GetChainCodeOwner:input_type -> GetChainCodeOwnerRequest
	24, // 12: FabricSDK.SetBaseURI:input_type -> SetBaseURIRequest
	26, // 13: FabricSDK.PublicMint:input_type -> PublicMintRequest
	28, // 14: FabricSDK.PrivateBurn:input_type -> PrivateBurnRequest
	18, // 15: FabricSDK.TotalSupply:input_type -> TokenURIRequest
	32, // 16: FabricSDK.Enroll:input_type -> EnrollRequest
	1,  // 17: FabricSDK.BalanceOf:output_type -> BalanceOfResponse
	3,  // 18: FabricSDK.OwnerOf:output_type -> OwnerOfResponse
	5,  // 19: FabricSDK.Approve:output_type -> ApproveResponse
	7,  // 20: FabricSDK.SetApprovalForAll:output_type -> SetApprovalForAllResponse
	9,  // 21: FabricSDK.IsApprovedForAll:output_type -> IsApprovedForAllResponse
	11, // 22: FabricSDK.GetApproved:output_type -> GetApprovedResponse
	13, // 23: FabricSDK.TransferFrom:output_type -> TransferFromResponse
	15, // 24: FabricSDK.ClientAccountBalance:output_type -> ClientAccountBalanceResponse
	17, // 25: FabricSDK.ClientAccountID:output_type -> ClientAccountIDResponse
	19, // 26: FabricSDK.TokenURI:output_type -> TokenURIReqponse
	21, // 27: FabricSDK.SetChainCodeOwner:output_type -> SetChainCodeOwnerResponse
	23, // 28: FabricSDK.GetChainCodeOwner:output_type -> GetChainCodeOwnerResponse
	25, // 29: FabricSDK.SetBaseURI:output_type -> SetBaseURIResponse
	27, // 30: FabricSDK.PublicMint:output_type -> PublicMintResponse
	29, // 31: FabricSDK.PrivateBurn:output_type -> PrivateBurnResponse
	31, // 32: FabricSDK.TotalSupply:output_type -> TotalSupplyResponse
	33, // 33: FabricSDK.Enroll:output_type -> EnrollResponse
	17, // [17:34] is the sub-list for method output_type
	0,  // [0:17] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fabricsdk_service_proto_init() }
func file_fabricsdk_service_proto_init() {
	if File_fabricsdk_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fabricsdk_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceOfResuest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceOfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnerOfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OwnerOfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetApprovalForAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetApprovalForAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsApprovedForAllRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsApprovedForAllResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApprovedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApprovedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFromRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferFromResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAccountBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAccountBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAccountIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAccountIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenURIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenURIReqponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetChainCodeOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetChainCodeOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChainCodeOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetChainCodeOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBaseURIRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBaseURIResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicMintRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicMintResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateBurnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivateBurnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalSupplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalSupplyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrollRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fabricsdk_service_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrollResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fabricsdk_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fabricsdk_service_proto_goTypes,
		DependencyIndexes: file_fabricsdk_service_proto_depIdxs,
		MessageInfos:      file_fabricsdk_service_proto_msgTypes,
	}.Build()
	File_fabricsdk_service_proto = out.File
	file_fabricsdk_service_proto_rawDesc = nil
	file_fabricsdk_service_proto_goTypes = nil
	file_fabricsdk_service_proto_depIdxs = nil
}
