// Code generated by "stringer -type=ErrCode --linecomment"; DO NOT EDIT.

package base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[InputError-1000]
	_ = x[OpenSqlError-1001]
	_ = x[ConnectSqlError-1002]
	_ = x[InsertError-1003]
	_ = x[QueryError-1004]
	_ = x[WrongLoginError-1005]
	_ = x[AccountExistError-1006]
	_ = x[PasswdUpdateError-1007]
	_ = x[AuthFailed-1101]
	_ = x[AuthFormatError-1102]
	_ = x[InvalidToken-1103]
	_ = x[GenTokenError-1104]
	_ = x[LackTokenError-1105]
	_ = x[UserTokenError-1105]
	_ = x[EnrollFail-1106]
	_ = x[GetPersonError-1201]
	_ = x[StoreEmailTokenError-1202]
	_ = x[ActivateEmailError-1203]
	_ = x[SendEmailError-1204]
	_ = x[TokenNotActivated-1205]
	_ = x[TokenInvalidError-1206]
	_ = x[TokenNotExist-1207]
	_ = x[TokenAlreadyActivated-1208]
	_ = x[WrongVerifyCode-1301]
	_ = x[ServerError-2000]
	_ = x[UserIDNotExist-3000]
	_ = x[UserProfileUpdateError-3001]
	_ = x[BalanceNotEnough-3002]
	_ = x[UpdateBalanceError-3003]
	_ = x[EditItemError-4001]
	_ = x[GetItemError-4002]
	_ = x[EmptyInput-1401]
	_ = x[EmailFormatError-1402]
	_ = x[PasswdLengthError-1403]
	_ = x[FileTypeError-1501]
	_ = x[FileSizeError-1502]
	_ = x[SigVerifyError-1601]
	_ = x[SigNotFound-1601]
	_ = x[SigCountError-1601]
}

const _ErrCode_name = "Operation succeedInput ErrorError open Mysql databaseCannot connect to mysql databaseInsert data errorQuery db errorWrong username or passwdAccount is already registeredUpdate password failedPermission denied, lack tokenThe auth format in the request header is incorrectThe token has expired or is invalid or could not parse with claimsGenerate token error: Sign Token FailedLack token in request headerRegister to Fabric failedCan not get user info from databaseStore Email Token ErrorActivate email token failedError sending activation email to the userToken not activated, please rerun activation emailToken invalid: OvertimeCould not find this token in databaseToken has already been activatedThe verify code is invalid or expiredInvalid Input: one of the parameters is emptyEmail format invalid or not related to ust emailPasswd not in valid lengthNot in format file type, recommended: jpg png jpeg gif jfif webp mp3 flac mp4 aviFile too large or could not parse and obtain file sizefailed to verify signatureServer ErrorUserIDNotExistUpdate profile failedSorry, your credit is running lowTransfer failedEditItemErrorGetItemError"

var _ErrCode_map = map[ErrCode]string{
	0:    _ErrCode_name[0:17],
	1000: _ErrCode_name[17:28],
	1001: _ErrCode_name[28:53],
	1002: _ErrCode_name[53:85],
	1003: _ErrCode_name[85:102],
	1004: _ErrCode_name[102:116],
	1005: _ErrCode_name[116:140],
	1006: _ErrCode_name[140:169],
	1007: _ErrCode_name[169:191],
	1101: _ErrCode_name[191:220],
	1102: _ErrCode_name[220:270],
	1103: _ErrCode_name[270:336],
	1104: _ErrCode_name[336:375],
	1105: _ErrCode_name[375:403],
	1106: _ErrCode_name[403:428],
	1201: _ErrCode_name[428:463],
	1202: _ErrCode_name[463:486],
	1203: _ErrCode_name[486:513],
	1204: _ErrCode_name[513:555],
	1205: _ErrCode_name[555:605],
	1206: _ErrCode_name[605:628],
	1207: _ErrCode_name[628:665],
	1208: _ErrCode_name[665:697],
	1301: _ErrCode_name[697:734],
	1401: _ErrCode_name[734:779],
	1402: _ErrCode_name[779:827],
	1403: _ErrCode_name[827:853],
	1501: _ErrCode_name[853:934],
	1502: _ErrCode_name[934:988],
	1601: _ErrCode_name[988:1014],
	2000: _ErrCode_name[1014:1026],
	3000: _ErrCode_name[1026:1040],
	3001: _ErrCode_name[1040:1061],
	3002: _ErrCode_name[1061:1094],
	3003: _ErrCode_name[1094:1109],
	4001: _ErrCode_name[1109:1122],
	4002: _ErrCode_name[1122:1134],
}

func (i ErrCode) String() string {
	if str, ok := _ErrCode_map[i]; ok {
		return str
	}
	return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
