// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/collections": {
            "get": {
                "description": "all collections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/collections",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/collections/{collection-id}": {
            "get": {
                "description": "single collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection id",
                        "name": "collection-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/collections/hahahah",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/collections/{collection-id}/items": {
            "get": {
                "description": "all items in collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection id",
                        "name": "collection-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/collections/hahahah/items",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event-banner": {
            "get": {
                "description": "event-banner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/event-banner",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "all events",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/events",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/{event-id}": {
            "get": {
                "description": "single event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/events/balala",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/items": {
            "get": {
                "description": "items in event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/events/balala/items",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/join": {
            "post": {
                "description": "user join event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST/api/v1/events/balala/join",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/likes": {
            "get": {
                "description": "item likes in event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/events/balala/likes",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/ranks": {
            "get": {
                "description": "item ranks in event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/events/balala/ranks",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/submit-item": {
            "post": {
                "description": "user submit item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item id",
                        "name": "item-id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST/api/v1/events/balala/submit-item",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/items": {
            "get": {
                "description": "all items",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/items",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/items/{item-id}": {
            "get": {
                "description": "single item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection id",
                        "name": "item-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/items/yiiiiiii",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tour": {
            "get": {
                "description": "tour",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/tour",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "user enroll",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST/api/v1/users",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "user login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST/api/v1/users",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/web-tutorial": {
            "get": {
                "description": "web tutorial",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/web-tutorial",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/what-is-nft": {
            "get": {
                "description": "what is nft",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/what-is-nft",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{id}": {
            "get": {
                "description": "get user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/Anna",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{id}/change-profile": {
            "post": {
                "description": "change profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "user name",
                        "name": "username",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST/api/v1/Anna/change-profile",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{id}/collected": {
            "get": {
                "description": "collected",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/Anna/collected",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{id}/create-collection": {
            "post": {
                "description": "create-collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collection name",
                        "name": "collection-name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST/api/v1/Anna/create-collection",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{id}/create-item": {
            "post": {
                "description": "create-item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item name",
                        "name": "item-name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST/api/v1/Anna/create-item",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{id}/creation": {
            "get": {
                "description": "creation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/Anna/creation",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{id}/edit-collection": {
            "post": {
                "description": "edit-collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collection name",
                        "name": "collection-name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST/api/v1/Anna/edit-collection",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{id}/edit-item": {
            "post": {
                "description": "edit-item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item name",
                        "name": "item-name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "POST/api/v1/Anna/edit-item",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{id}/favorites": {
            "get": {
                "description": "favorites",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "GET/api/v1/Anna/favorites",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "HKUST-NFT",
	Description:      "HKUST-NFT Server API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
