// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/collections": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagenumber",
                        "name": "pagenumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "method on how to sort these collections",
                        "name": "method",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    }
                }
            }
        },
        "/collections/{collection-id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collection"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection id",
                        "name": "collection-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/event-banner": {
            "get": {
                "description": "event-banner",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "all events",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/events/{event-id}": {
            "get": {
                "description": "single event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/items": {
            "get": {
                "description": "items in event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/join": {
            "post": {
                "description": "user join event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/likes": {
            "post": {
                "description": "user join event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "item id",
                        "name": "item-id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/ranks": {
            "get": {
                "description": "item ranks in event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/events/{event-id}/submit-item": {
            "post": {
                "description": "user submit item",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "event"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "event id",
                        "name": "event-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "item id",
                        "name": "item-id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/items": {
            "get": {
                "description": "get all items in database and get them sorted according to \"method\", default time",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagenumber",
                        "name": "pagenumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "method on how to sort these items",
                        "name": "method",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    }
                }
            }
        },
        "/items/item-json": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "token id of one NFT",
                        "name": "token-id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/items/{item-id}": {
            "get": {
                "description": "single item according to item-id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "item"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "item-id",
                        "name": "item-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/tour": {
            "get": {
                "description": "tour",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/tr/articles": {
            "get": {
                "description": "tutorials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/tr/articles/:articles-id": {
            "post": {
                "description": "view articles by title",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tour"
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/users/activate": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "token of email(different from auth jwt token)",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/users/forget-passwd": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "passwd",
                        "name": "passwd",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "passwd",
                        "name": "passwd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the user's name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/users/rerun-Email": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/users/reset-passwd": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/users/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "passwd",
                        "name": "passwd",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "newpasswd",
                        "name": "newpasswd",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/{id}/collected": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagenumber",
                        "name": "pagenumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    }
                }
            }
        },
        "/{id}/create-collection": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "logo-image",
                        "name": "logo-image",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "feature-image",
                        "name": "feature-image",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "banner-image",
                        "name": "banner-image",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "description",
                        "name": "description",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/{id}/create-item": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "image",
                        "name": "image",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "description",
                        "name": "description",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collection",
                        "name": "collection",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "category",
                        "name": "category",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "label",
                        "name": "label",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/{id}/creation": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagenumber",
                        "name": "pagenumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    }
                }
            }
        },
        "/{id}/delete-collection": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection-id",
                        "name": "collection-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/{id}/delete-item": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "item-id",
                        "name": "item-id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/{id}/edit-collection": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "logo-image",
                        "name": "logo-image",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "feature-image",
                        "name": "feature-image",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "banner-image",
                        "name": "banner-image",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "description",
                        "name": "description",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/{id}/edit-item": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "image",
                        "name": "image",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "description",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "collection",
                        "name": "collection",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "label",
                        "name": "label",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/{id}/edit-profile": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "banner-image",
                        "name": "banner-image",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "avatar-image",
                        "name": "avatar-image",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "poison",
                        "name": "poison",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "campus",
                        "name": "campus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/{id}/favorites": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "pagenumber",
                        "name": "pagenumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "pagesize",
                        "name": "pagesize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.PageResponse"
                        }
                    }
                }
            }
        },
        "/{id}/get-user": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "responses": {
                    "200": {
                        "description": "Operation Succeed",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    },
                    "400": {
                        "description": "request error",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "error code and message and nil data",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "base.PageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码",
                    "type": "integer"
                },
                "data": {
                    "description": "返回数据"
                },
                "msg": {
                    "description": "错误描述",
                    "type": "string"
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "base.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "错误码",
                    "type": "integer"
                },
                "data": {
                    "description": "返回数据"
                },
                "msg": {
                    "description": "错误描述",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "HKUST-NFT",
	Description:      "HKUST-NFT Server API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
